/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Aa */

#ifndef _Included_Aa
#define _Included_Aa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Aa
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Aa_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
