/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethodExample */

#ifndef _Included_NativeMethodExample
#define _Included_NativeMethodExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethodExample
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethodExample_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
